brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
namesrvAddr=namesrv:9876
brokerIP1=127.0.0.1
autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true
deleteWhen=04
fileReservedTime=48
