port 26379
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
sentinel monitor redis-v2-master redis-sentinel-master 6379 2
sentinel down-after-milliseconds redis-v2-master 3000
sentinel failover-timeout redis-v2-master 15000
sentinel parallel-syncs redis-v2-master 1
