brokerClusterName=ReliabilityV2Cluster
brokerName=broker-reliability-v2
brokerId=0
namesrvAddr=mq-v2-namesrv:9876
brokerIP1=127.0.0.1
listenPort=11911
haListenPort=11912
fastListenPort=11909
autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true
deleteWhen=04
fileReservedTime=48
transactionCheckInterval=6000
transactionTimeOut=6000
transactionCheckMax=5
