server:
  port: 8090

spring:
  application:
    name: redis-cache-specialization-v2
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/redis_cache_specialization_v2?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: redis_v2
    password: redis_v2
  data:
    redis:
      host: 127.0.0.1
      port: 6380
      timeout: 200ms
  flyway:
    enabled: true

app:
  cache:
    key-prefix: "middleware:v2:schedule:"
    ttl: 5m
    ttl-jitter: 30s
    missing-ttl: 30s
    logical-ttl: 30s
    logical-stale-limit: 2m
    lock-wait: 200ms
    lock-lease: 3s
    database-fallback-permits: 8
  invalidation:
    fixed-delay: 5s
    batch-size: 50
    max-retries: 8
  redisson:
    address: "redis://127.0.0.1:6380"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: redis-cache-specialization-v2
